[package]
name = "solitaire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
rand = "0.8.5"

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["image"]